/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtrlCliente;
import Controller.CtrlDeposito;
import Controller.CtrlEstoque;
import Controller.CtrlProduto;
import Model.Armazem;
import Model.Cliente;
import Model.Deposito;
import Model.Estoque;
import Model.ItemRemessa;
import Model.Produto;
import Model.Remessa;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import transportadoraifes.Util;

/**
 *
 * @author Igor Ferrani
 */
public class FormCadastroRemessa extends javax.swing.JFrame {

    DefaultListModel dataListItem = new DefaultListModel();
    private FormCadastroViagem formCadastroViagem;
    
    /**
     * Creates new form FormCadastroCaminhao
     */
    public FormCadastroRemessa() {
        initComponents();
        init();
        //FormCadastroViagem formCadastroViagem = cadastroViagem;
        
        //System.out.println(formCadastroViagem);
    }
    
    public FormCadastroRemessa(FormCadastroViagem cadastroViagem) {
        formCadastroViagem = cadastroViagem;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputDeposito = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JList<>();
        inserirItem = new javax.swing.JButton();
        removerItem = new javax.swing.JButton();
        inputProduto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNumRemessa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputCliente = new javax.swing.JComboBox<>();
        inputValorProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputQtdProduto = new javax.swing.JSpinner();
        inputQtdEstoque = new javax.swing.JTextField();
        inputHoraEntrega = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        inputDataEntrega = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCancelarRemessa = new javax.swing.JButton();
        btnSalvarAlteracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da remessa"));

        inputDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDepositoActionPerformed(evt);
            }
        });

        jLabel1.setText("Depósito (destino)");

        jScrollPane2.setViewportView(listItem);

        inserirItem.setText("Inserir");
        inserirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirItemActionPerformed(evt);
            }
        });

        removerItem.setText("Remover item");
        removerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerItemActionPerformed(evt);
            }
        });

        inputProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Qtd. em estoque");

        jLabel5.setText("Produto");

        jLabel6.setText("Valor R$");

        jLabel2.setText("Cliente");

        inputNumRemessa.setText("REM001");
        inputNumRemessa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumRemessaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nº remessa");

        inputCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClienteActionPerformed(evt);
            }
        });

        inputValorProduto.setEnabled(false);

        jLabel8.setText("Qtd. à transportar");

        inputQtdEstoque.setEnabled(false);

        inputHoraEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel7.setText("Hora de entrega");

        inputDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        inputDataEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDataEntregaActionPerformed(evt);
            }
        });

        jLabel9.setText("Data de entrega");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 130, Short.MAX_VALUE))
                            .addComponent(inputCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(inputNumRemessa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removerItem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inserirItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(inputDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE))
                                    .addComponent(inputHoraEntrega)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(inputProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(inputValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(inputQtdProduto))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNumRemessa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inserirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removerItem)))
                .addGap(42, 42, 42))
        );

        btnCancelarRemessa.setText("Cancelar");
        btnCancelarRemessa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRemessaActionPerformed(evt);
            }
        });

        btnSalvarAlteracoes.setText("Salvar alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarRemessa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarAlteracoes)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarRemessa)
                    .addComponent(btnSalvarAlteracoes))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerItemActionPerformed
        // TODO add your handling code here:
        int index = listItem.getSelectedIndex();
        removeListItem(index);
    }//GEN-LAST:event_removerItemActionPerformed

    private void btnCancelarRemessaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRemessaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarRemessaActionPerformed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        // TODO add your handling code here:
        // String codRemessa = inputCodRemessa.getText();
        /*if(!"".equals(codRemessa)){
            // percorre a listagem para editar o existente
        } else {*/
            int codDeposito = inputDeposito.getItemAt(inputDeposito.getSelectedIndex()).getCodDeposito();
            String numRemessa = inputNumRemessa.getText();
            String nomCliente = inputCliente.getItemAt(inputCliente.getSelectedIndex()).getNomCliente();
            String nomDeposito = inputDeposito.getItemAt(inputDeposito.getSelectedIndex()).getNomDeposito();
            
            // insere um novo
            Remessa remessa = new Remessa();
            remessa.setCodDeposito(codDeposito);
            remessa.setNumRemessa(numRemessa);
            remessa.setArrayItemRemessa(dataListItem);
            remessa.setNomCliente(nomCliente);
            remessa.setNomDeposito(nomDeposito);
            
            if(dataListItem.getSize() > 0){
                formCadastroViagem.addListItem(remessa);
                this.setVisible(false);
            } else {
                Util.showMessage("Informe ao menos 1 item de produto para a remessa");
            }
        //}
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void inputNumRemessaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumRemessaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumRemessaActionPerformed

    private void inputProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProdutoActionPerformed
        // TODO add your handling code here:
        if(inputProduto.getSelectedIndex() >= 0){
            double valorProduto = inputProduto.getItemAt(inputProduto.getSelectedIndex()).getValProduto();
            inputValorProduto.setText(Double.toString(valorProduto));
            setQtdProdutoEstoque();
        }
    }//GEN-LAST:event_inputProdutoActionPerformed

    private void inputDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDepositoActionPerformed
        // codigo
    }//GEN-LAST:event_inputDepositoActionPerformed

    private void inputClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClienteActionPerformed
        // TODO add your handling code here:
        setSelectDeposito();
        setSelectProduto();
    }//GEN-LAST:event_inputClienteActionPerformed

    private void inserirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirItemActionPerformed
        if(inputProduto.getSelectedIndex() >= 0){
            int codProduto = inputProduto.getItemAt(inputProduto.getSelectedIndex()).getCodProduto();
            Produto produto = inputProduto.getItemAt(inputProduto.getSelectedIndex());
            int qtdProduto = (Integer) inputQtdProduto.getValue();
            double qtdProdutoEstoque = Double.parseDouble(inputQtdEstoque.getText());

            if(qtdProdutoEstoque >= qtdProduto){
                if(qtdProduto > 0){
                    ItemRemessa itemRemessa = new ItemRemessa();
                    itemRemessa.setCodProduto(codProduto);
                    itemRemessa.setQtdProduto(qtdProduto);
                    itemRemessa.setProduto(produto);
                    addListItem(itemRemessa);
                    resetItem();
                } else {
                    Util.showMessage("É preciso informar a quantidade para o produto");
                }
            } else {
                Util.showMessage("Não existe quantidade suficiente no armazem atual");
            }
        } else {
            Util.showMessage("Informe o produto");
        }
    }//GEN-LAST:event_inserirItemActionPerformed

    private void inputDataEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDataEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDataEntregaActionPerformed
    
    private static final DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private static final DateTimeFormatter hourFormat = DateTimeFormatter.ofPattern("HH:mm");
    
    public void setDataHoraDespacho(){
        LocalDateTime now = LocalDateTime.now();
	inputDataEntrega.setText(dateFormat.format(now));
        inputHoraEntrega.setText(hourFormat.format(now));
    }
    
    public void resetItem(){
        inputQtdProduto.setValue(0);
    }
    
    public void addListItem(ItemRemessa itemRemessa){
        dataListItem.addElement(itemRemessa);
        listItem.setModel(dataListItem);
        blockModifyCliente();
    }
    
    public void removeListItem(int index){
        if(index >= 0){
            dataListItem.remove(index);
            //listItem.setModel(dataListItem);
            blockModifyCliente();
        }
    }
    
    public void init(){
        setSelectCliente();
        setSelectDeposito();
        setQtdProdutoEstoque();
        setDataHoraDespacho();
        blockModifyCliente();
    }
    
    public void setSelectDeposito(){
        inputDeposito.removeAllItems();
        
        try {
            if(inputCliente.getSelectedIndex() >= 0){
                int codCliente = inputCliente.getItemAt(inputCliente.getSelectedIndex()).getCodCliente();
                Deposito deposito = new Deposito();
                deposito.setCodCliente(codCliente);
                
                CtrlDeposito ctrlDeposito = new CtrlDeposito();
                ctrlDeposito.setComboBox(inputDeposito, deposito);
            }
        } catch(SQLException e){
            Util.showCatch(e.getMessage());
        } catch(Exception e){
            Util.showCatch(e.getMessage());
        }
    }
    
    public void setSelectCliente(){
        inputCliente.removeAllItems();
        CtrlCliente ctrlCliente = new CtrlCliente();
        try {
            ctrlCliente.setComboBox(inputCliente);
        } catch(SQLException e){
            Util.showCatch(e.getMessage());
        } catch(Exception e){
            Util.showCatch(e.getMessage());
        }
    }
    
    public void setSelectedDeposito(Deposito deposito){
        inputDeposito.removeAllItems();
        try {
            CtrlDeposito ctrlDeposito = new CtrlDeposito();
            ctrlDeposito.setSelectedComboBox(deposito, inputDeposito);
        } catch(SQLException e){
            Util.showCatch(e.getMessage());
        } catch(Exception e){
            Util.showCatch(e.getMessage());
        }
    }
    
    public void setSelectProduto(){
        int codCliente = inputCliente.getItemAt(inputCliente.getSelectedIndex()).getCodCliente();
        inputProduto.removeAllItems();
        int codArmazem = formCadastroViagem.getModelArmazem().getCodArmazem();
        
        CtrlProduto ctrlProduto = new CtrlProduto();
        Produto produto = new Produto();
        produto.setCodCliente(codCliente);
        Estoque estoque = new Estoque();
        estoque.setCodArmazem(codArmazem);
        try {
            ctrlProduto.setComboBox(inputProduto, produto, estoque);
        } catch(SQLException e){
            Util.showCatch(e.getMessage());
        } catch(Exception e){
            Util.showCatch(e.getMessage());
        }
    }
    
    public void setValorProduto(double valor){
        inputValorProduto.setText(Double.toString(valor));
    }
    
    private void setQtdProdutoEstoque(){
        try {
            if(inputProduto.getSelectedIndex() >= 0){
                Armazem armazem = formCadastroViagem.getModelArmazem();
                Estoque estoque = new Estoque();
                estoque.setCodArmazem(armazem.getCodArmazem());
                estoque.setCodProduto(inputProduto.getItemAt(inputProduto.getSelectedIndex()).getCodProduto());

                CtrlEstoque ctrlEstoque = new CtrlEstoque();
                ctrlEstoque.setInputQtdProdutoPorEstoque(inputQtdEstoque, estoque);
            }
        } catch(SQLException e){
            Util.showCatch(e.getMessage());
        } catch(Exception e){
            Util.showCatch(e.getMessage());
        }
    }
    
    public void blockModifyCliente(){
        int len = dataListItem.getSize();
        boolean enabled = false;
        if(len <= 0)
            enabled = true;
        
        inputCliente.setEnabled(enabled);
        inputDeposito.setEnabled(enabled);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroRemessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroRemessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroRemessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroRemessa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroRemessa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRemessa;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JComboBox<Cliente> inputCliente;
    private javax.swing.JFormattedTextField inputDataEntrega;
    private javax.swing.JComboBox<Deposito> inputDeposito;
    private javax.swing.JFormattedTextField inputHoraEntrega;
    private javax.swing.JTextField inputNumRemessa;
    private javax.swing.JComboBox<Produto> inputProduto;
    private javax.swing.JTextField inputQtdEstoque;
    private javax.swing.JSpinner inputQtdProduto;
    private javax.swing.JTextField inputValorProduto;
    private javax.swing.JButton inserirItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<ItemRemessa> listItem;
    private javax.swing.JButton removerItem;
    // End of variables declaration//GEN-END:variables
}
